services:
  dockhand:
    image: fnsys/dockhand:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    networks:
      - main_app_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  dockhand_data:

networks:
  main_app_net:
    external: true
    name: caddy_app_net
